In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_columns', None)
df = pd.read_csv('movie_reccomender.csv')

In [27]:
df2.head()

,movie,year,timeMin,imdb,metascore,votes,grossMillions,genre,description,director,actors
0,Dark,2017,60.0,8.8,-,"215,184",-,"['Crime', ' Drama', ' Mystery ']","A family saga with a supernatural twist, set i...","Stars:Louis Hofmann, Karoline ...","Stars:Louis Hofmann, Karoline ..."
1,The Sinner,2017,45.0,8.0,-,"77,161",-,"['Crime', ' Drama', ' Mystery ']",Anthology series that examines how and why ord...,"Stars:Bill Pullman, Dohn Norwo...","Stars:Bill Pullman, Dohn Norwo..."
2,Game of Thrones,2011,57.0,9.3,-,"1,688,494",-,"['Action', ' Adventure', ' Drama ']",Nine noble families fight for control over the...,"Stars:Emilia Clarke, Peter Din...","Stars:Emilia Clarke, Peter Din..."
3,Yellowstone,2018,60.0,8.4,-,"17,372",-,"['Drama', ' Western ']",A ranching family in Montana faces off against...,"Stars:Kevin Costner, Luke Grim...","Stars:Kevin Costner, Luke Grim..."
4,Knives Out,2019,130.0,7.9,82,"341,615",$165.36M,"['Comedy', ' Crime', ' Drama ']",A detective investigates the death of a patria...,Director:Rian Johnson| Stars:Daniel Cr...,Director:Rian Johnson| Stars:Daniel Cr...

In [5]:
df.drop(df.columns[0], axis=1, inplace=True)

In [6]:
df.loc[df.duplicated(keep='first'), :]

,movie,year,timeMin,imdb,metascore,votes,grossMillions,genre,description,movieStars
9999,The Invisible Guardian,(2017),129 min,6.3,-,"9,531",-,['Thriller '],A female inspector confronts a serial killer w...,Director:Fernando Gonz√°lez Molina| Sta...
10000,Death Warrant,(1990),89 min,5.7,34,"16,675",$16.85M,"['Action', ' Crime', ' Mystery ']","In a violent and corrupt prison, decorated cop...",Director:Deran Sarafian| Stars:Jean-Cl...
10001,A Shaun the Sheep Movie: Farmageddon,(2019),86 min,6.9,79,"7,322",-,"['Animation', ' Adventure', ' Comedy ...",When an alien with amazing powers crash-lands ...,"Directors:Will Becher, Richard Phelan| ..."
10002,Days of the Bagnold Summer,(2019),86 min,6.7,60,484,-,['Comedy '],A teenager spends his summer listening to heav...,Director:Simon Bird| Stars:Tamsin Grei...
10003,Soundtrack,(2019),56 min,6.7,-,"1,501",-,"['Drama', ' Musical ']",Music connects the lives of random people livi...,"Stars:Paul James, Callie Herna..."
...,...,...,...,...,...,...,...,...,...,...
29993,Brooklyn Nine-Nine,(2013‚Äì ),22 min,8.4,-,"198,907",-,"['Comedy', ' Crime ']","""Brooklyn Nine-Nine"" follows the exploits of h...","Stars:Andy Samberg, Stephanie ..."
29994,The Gentlemen,(2019),113 min,7.9,51,"157,584",-,"['Action', ' Comedy', ' Crime ']",An American expat tries to sell off his highly...,Director:Guy Ritchie| Stars:Matthew Mc...
29995,The Blacklist,(2013‚Äì ),43 min,8.0,-,"182,986",-,"['Crime', ' Drama', ' Mystery ']","A new FBI profiler, Elizabeth Keen, has her en...","Stars:James Spader, Megan Boon..."
29996,Better Call Saul,(2015‚Äì ),46 min,8.7,-,"298,343",-,"['Crime', ' Drama ']",The trials and tribulations of criminal lawyer...,"Stars:Bob Odenkirk, Rhea Seeho..."
29997,Parasite,(2019),132 min,8.6,96,"442,417",$53.37M,"['Comedy', ' Drama', ' Thriller ']",Greed and class discrimination threaten the ne...,Director:Bong Joon Ho| Stars:Kang-ho S...

In [ ]:
# Dropping all duplicate rows

In [7]:
df1 = df.drop_duplicates()

In [8]:
df2 = df1.drop_duplicates(subset='movie')

In [9]:
df2.shape

(9625, 10)

In [66]:
df2.isnull().sum()

movie            0
year             0
timeMin          0
imdb             0
metascore        0
votes            0
grossMillions    0
genre            0
description      0
director         0
actors           0
dtype: int64

In [ ]:
df2['actors'] = df2['movieStars']
df2.rename(columns={'movieStars': 'director'}, inplace=True)

In [63]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9625 entries, 0 to 9998
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   movie          9625 non-null   object
 1   year           9625 non-null   int32
 2   timeMin        9625 non-null   int32
 3   imdb           9625 non-null   float64
 4   metascore      9625 non-null   object
 5   votes          9625 non-null   int32
 6   grossMillions  9625 non-null   object
 7   genre          9625 non-null   object
 8   description    9625 non-null   object
 9   director       9622 non-null   object
 10  actors         9622 non-null   object
dtypes: float64(1), int32(3), object(7)
memory usage: 1.1+ MB

In [ ]:
# removing symbols and changing type of columns

df2['year'] = df2['year'].str.extract('(\d+)').astype(int)

df2['timeMin'] = df2['timeMin'].replace('min', '').astype(float)
df2['timeMin'] = pd.to_numeric(df2['timeMin'], errors='coerce')
df2['timeMin'] = df2['timeMin'].fillna(0)
df2['timeMin'] = df2['timeMin'].astype(int)

df2['votes'] = df2['votes'].str.replace(',', '').astype(float)
df2['votes'] = df2['votes'].astype(int)

df2['metascore'] = df2['metascore'].str.extract('(\d+)')
df2['metascore'] = pd.to_numeric(df2['metascore'], errors='coerce')

df2['grossMillions'] = df2['grossMillions'].map(lambda x: x.lstrip('$').rstrip('M'))
df2['grossMillions'] = pd.to_numeric(df2['grossMillions'], errors='coerce')

In [325]:
df13.head(20)

,movie,year,timeMin,imdb,metascore,votes,grossMillions,genre,description,director,actors
0,Dark,2017,60,8.8,unknown,215184,unknown,"['Crime', ' Drama', ' Mystery ']","A family saga with a supernatural twist, set i...",unknown,"Louis Hofmann, Karoline Eichhorn, Lisa Vicari,..."
1,The Sinner,2017,45,8.0,unknown,77161,unknown,"['Crime', ' Drama', ' Mystery ']",Anthology series that examines how and why ord...,unknown,"Bill Pullman, Dohn Norwood, Adam LeFevre, Jess..."
2,Game of Thrones,2011,57,9.3,unknown,1688494,unknown,"['Action', ' Adventure', ' Drama ']",Nine noble families fight for control over the...,unknown,"Emilia Clarke, Peter Dinklage, Kit Harington, ..."
3,Yellowstone,2018,60,8.4,unknown,17372,unknown,"['Drama', ' Western ']",A ranching family in Montana faces off against...,unknown,"Kevin Costner, Luke Grimes, Kelly Reilly, Wes ..."
4,Knives Out,2019,130,7.9,82,341615,165.36,"['Comedy', ' Crime', ' Drama ']",A detective investigates the death of a patria...,Rian Johnson,"Daniel Craig, Chris Evans, Ana de Armas, Jamie..."
5,The Order,2019,60,6.9,unknown,16064,unknown,"['Drama', ' Fantasy', ' Horror ']","Out to avenge his mother's death, a college st...",unknown,"Jake Manley, Sarah Grey, Adam DiMarco, Kathari..."
6,Love,2015,135,6.1,51,44018,unknown,"['Drama', ' Romance ']",Murphy is an American living in Paris who ente...,Gaspar No√©,"Aomi Muyock, Karl Glusman, Klara Kristin, Juan..."
7,Community,2009,22,8.5,unknown,199544,unknown,['Comedy '],A suspended lawyer is forced to enroll in a co...,unknown,"Joel McHale, Danny Pudi, Donald Glover, Chevy ..."
8,The Office,2005,22,8.9,unknown,367436,unknown,['Comedy '],A mockumentary on a group of typical office wo...,unknown,"Steve Carell, Jenna Fischer, John Krasinski, R..."
9,Doctor Sleep,2019,152,7.4,59,110375,unknown,"['Drama', ' Fantasy', ' Horror ']",Years following the events of The Shining (198...,Mike Flanagan,"Ewan McGregor, Rebecca Ferguson, Kyliegh Curra..."
10,Breaking Bad,2008,49,9.5,unknown,1370769,unknown,"['Crime', ' Drama', ' Thriller ']",A high school chemistry teacher diagnosed with...,unknown,"Bryan Cranston, Aaron Paul, Anna Gunn, Betsy B..."
11,Grey's Anatomy,2005,41,7.6,unknown,235748,unknown,"['Drama', ' Romance ']",A drama centered on the personal and professio...,unknown,"Ellen Pompeo, Chandra Wilson, James Pickens Jr..."
12,The 100,2014,43,7.7,unknown,197555,unknown,"['Drama', ' Mystery', ' Sci-Fi ']",Set ninety-seven years after a nuclear war has...,unknown,"Eliza Taylor, Bob Morley, Marie Avgeropoulos, ..."
13,Ozark,2017,60,8.4,unknown,161744,unknown,"['Crime', ' Drama', ' Thriller ']",A financial advisor drags his family from Chic...,unknown,"Jason Bateman, Laura Linney, Sofia Hublitz, Sk..."
14,Supernatural,2005,44,8.4,unknown,375575,unknown,"['Drama', ' Fantasy', ' Horror ']",Two brothers follow their father's footsteps a...,unknown,"Jared Padalecki, Jensen Ackles, Jim Beaver, Mi..."
15,Doom Patrol,2019,60,8.0,unknown,26787,unknown,"['Action', ' Adventure', ' Comedy ']",The adventures of an idealistic mad scientist ...,unknown,"Diane Guerrero, April Bowlby, Matt Bomer, Bren..."
16,The Boys,2019,60,8.7,unknown,151182,unknown,"['Action', ' Comedy', ' Crime ']",A group of vigilantes set out to take down cor...,unknown,"Karl Urban, Jack Quaid, Antony Starr, Erin Mor..."
17,The Politician,2019,42,7.5,unknown,15170,unknown,"['Comedy', ' Drama ']","Payton Hobart, a student from Santa Barbara, h...",unknown,"Ben Platt, Zoey Deutch, Lucy Boynton, Julia Sc..."
18,13 Reasons Why,2017,60,7.7,unknown,244190,unknown,"['Drama', ' Mystery ']","Follows teenager Clay Jensen, in his quest to ...",unknown,"Dylan Minnette, Katherine Langford, Christian ..."
19,Vikings,2013,44,8.5,unknown,395873,unknown,"['Action', ' Adventure', ' Drama ']",Vikings transports us to the brutal and myster...,unknown,"Katheryn Winnick, Gustaf Skarsg√•rd, Alexander ..."

In [ ]:
# replacing Nan values

df2['metascore'] = df2['metascore'].replace(np.nan, 'unknown')
df2['grossMillions'] = df2['grossMillions'].replace(np.nan, 'unknown')
df2['director'] = df2['director'].replace(np.nan, 'unknown')
df2['actors'] = df2['actors'].replace(np.nan, 'unknown')

In [274]:
# reversing and spliting Cast column into two different columns

df8['director']=df8['director'].fillna("")

df8['director'] = df8['director'].apply(lambda x: pd.Series(x.split('|')[::-1][-1]))

df8['actors']=df8['actors'].fillna("")

df8['actors'] = df8['actors'].apply(lambda x: pd.Series(x.split('|')[::-1][0]))

In [286]:
# removing dups and final swap

is_duplicate = df8.apply(pd.Series.duplicated, axis=1)
df10 = df8.where(~is_duplicate, 'unknown')

wrongDataIdx = (df10['actors'] == 'unknown')
df10.loc[wrongDataIdx, ['director', 'actors']] = df10.loc[wrongDataIdx, ['actors', 'director']].values

In [323]:
df14 = df13.copy()

In [294]:
# deleting all characters except names

df10['director'] = df10['director'].apply(lambda x: x.split(':')[-1])

df10['actors'] = df10['actors'].apply(lambda x: x.split(':')[-1])

In [93]:
# getting genres out of a loop and removing characters

import re
full_pattern = re.compile('[^a-zA-Z\\\/]|_')
data['genre'] = data['genre'].apply(lambda x: re.sub(full_pattern, ' ', x))

In [ ]:
data.to_csv('cleaned_data.csv', index=False)